spring:
  application:
  name: dm-gateway-zuul
server:
  port: 7600

zuul:
  routes:
  dm-user-consumer: /demo/**
eureka:
  client:
  service-url:
  defaultZone: http://admin:admin123@localhost:7077/eureka/
